// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(MiqatFFI)
import MiqatFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_miqat_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_miqat_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMiqatInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol HijriDateInfoProtocol: AnyObject, Sendable {
    
    func date()  -> HijriDate
    
    func events()  -> [IslamicEvent]
    
    /**
     * Converts this Hijri date back to a Unix timestamp (seconds) at midnight UTC,
     * or `None` if the date cannot be represented.
     */
    func toGregorian()  -> Int64?
    
}
open class HijriDateInfo: HijriDateInfoProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_miqat_fn_clone_hijridateinfo(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_miqat_fn_free_hijridateinfo(handle, $0) }
    }

    
public static func fromTimestamp(timestampSecs: Int64) -> HijriDateInfo  {
    return try!  FfiConverterTypeHijriDateInfo_lift(try! rustCall() {
    uniffi_miqat_fn_constructor_hijridateinfo_from_timestamp(
        FfiConverterInt64.lower(timestampSecs),$0
    )
})
}
    

    
open func date() -> HijriDate  {
    return try!  FfiConverterTypeHijriDate_lift(try! rustCall() {
    uniffi_miqat_fn_method_hijridateinfo_date(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func events() -> [IslamicEvent]  {
    return try!  FfiConverterSequenceTypeIslamicEvent.lift(try! rustCall() {
    uniffi_miqat_fn_method_hijridateinfo_events(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Converts this Hijri date back to a Unix timestamp (seconds) at midnight UTC,
     * or `None` if the date cannot be represented.
     */
open func toGregorian() -> Int64?  {
    return try!  FfiConverterOptionInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_hijridateinfo_to_gregorian(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHijriDateInfo: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HijriDateInfo

    public static func lift(_ handle: UInt64) throws -> HijriDateInfo {
        return HijriDateInfo(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HijriDateInfo) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HijriDateInfo {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HijriDateInfo, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHijriDateInfo_lift(_ handle: UInt64) throws -> HijriDateInfo {
    return try FfiConverterTypeHijriDateInfo.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHijriDateInfo_lower(_ value: HijriDateInfo) -> UInt64 {
    return FfiConverterTypeHijriDateInfo.lower(value)
}






public protocol PrayerTimesProtocol: AnyObject, Sendable {
    
    func asr()  -> Int64
    
    func currentPrayer()  -> Prayer
    
    func dhuhr()  -> Int64
    
    func fajr()  -> Int64
    
    func fajrTomorrow()  -> Int64
    
    func hijriDate()  -> HijriDate
    
    func ishaa()  -> Int64
    
    func maghrib()  -> Int64
    
    func nextPrayer()  -> Prayer
    
    func sunrise()  -> Int64
    
}
open class PrayerTimes: PrayerTimesProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_miqat_fn_clone_prayertimes(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_miqat_fn_free_prayertimes(handle, $0) }
    }

    
public static func fromMethod(dateUtcTimestampSecs: Int64, coordinates: Coordinates, method: Method) -> PrayerTimes  {
    return try!  FfiConverterTypePrayerTimes_lift(try! rustCall() {
    uniffi_miqat_fn_constructor_prayertimes_from_method(
        FfiConverterInt64.lower(dateUtcTimestampSecs),
        FfiConverterTypeCoordinates_lower(coordinates),
        FfiConverterTypeMethod_lower(method),$0
    )
})
}
    
public static func fromPrecomputed(dateUtcTimestampSecs: Int64, provider: Provider) -> PrayerTimes  {
    return try!  FfiConverterTypePrayerTimes_lift(try! rustCall() {
    uniffi_miqat_fn_constructor_prayertimes_from_precomputed(
        FfiConverterInt64.lower(dateUtcTimestampSecs),
        FfiConverterTypeProvider_lower(provider),$0
    )
})
}
    

    
open func asr() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_asr(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func currentPrayer() -> Prayer  {
    return try!  FfiConverterTypePrayer_lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_current_prayer(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func dhuhr() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_dhuhr(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func fajr() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_fajr(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func fajrTomorrow() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_fajr_tomorrow(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func hijriDate() -> HijriDate  {
    return try!  FfiConverterTypeHijriDate_lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_hijri_date(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func ishaa() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_ishaa(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func maghrib() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_maghrib(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func nextPrayer() -> Prayer  {
    return try!  FfiConverterTypePrayer_lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_next_prayer(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sunrise() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_miqat_fn_method_prayertimes_sunrise(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrayerTimes: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PrayerTimes

    public static func lift(_ handle: UInt64) throws -> PrayerTimes {
        return PrayerTimes(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PrayerTimes) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrayerTimes {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PrayerTimes, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrayerTimes_lift(_ handle: UInt64) throws -> PrayerTimes {
    return try FfiConverterTypePrayerTimes.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrayerTimes_lower(_ value: PrayerTimes) -> UInt64 {
    return FfiConverterTypePrayerTimes.lower(value)
}




public struct Coordinates: Equatable, Hashable {
    public let latitude: Double
    public let longitude: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(latitude: Double, longitude: Double) {
        self.latitude = latitude
        self.longitude = longitude
    }

    

    
}

#if compiler(>=6)
extension Coordinates: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoordinates: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Coordinates {
        return
            try Coordinates(
                latitude: FfiConverterDouble.read(from: &buf), 
                longitude: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Coordinates, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.latitude, into: &buf)
        FfiConverterDouble.write(value.longitude, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinates_lift(_ buf: RustBuffer) throws -> Coordinates {
    return try FfiConverterTypeCoordinates.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinates_lower(_ value: Coordinates) -> RustBuffer {
    return FfiConverterTypeCoordinates.lower(value)
}


public struct HijriDate: Equatable, Hashable {
    public let year: Int32
    public let month: UInt8
    public let day: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(year: Int32, month: UInt8, day: UInt8) {
        self.year = year
        self.month = month
        self.day = day
    }

    

    
}

#if compiler(>=6)
extension HijriDate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHijriDate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HijriDate {
        return
            try HijriDate(
                year: FfiConverterInt32.read(from: &buf), 
                month: FfiConverterUInt8.read(from: &buf), 
                day: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: HijriDate, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.year, into: &buf)
        FfiConverterUInt8.write(value.month, into: &buf)
        FfiConverterUInt8.write(value.day, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHijriDate_lift(_ buf: RustBuffer) throws -> HijriDate {
    return try FfiConverterTypeHijriDate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHijriDate_lower(_ value: HijriDate) -> RustBuffer {
    return FfiConverterTypeHijriDate.lower(value)
}


/**
 * An occurrence of an Islamic event with its associated Hijri date and Gregorian timestamp.
 */
public struct IslamicEventOccurrence: Equatable, Hashable {
    public let event: IslamicEvent
    public let hijriDate: HijriDate
    public let gregorianTimestampSecs: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(event: IslamicEvent, hijriDate: HijriDate, gregorianTimestampSecs: Int64) {
        self.event = event
        self.hijriDate = hijriDate
        self.gregorianTimestampSecs = gregorianTimestampSecs
    }

    

    
}

#if compiler(>=6)
extension IslamicEventOccurrence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIslamicEventOccurrence: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IslamicEventOccurrence {
        return
            try IslamicEventOccurrence(
                event: FfiConverterTypeIslamicEvent.read(from: &buf), 
                hijriDate: FfiConverterTypeHijriDate.read(from: &buf), 
                gregorianTimestampSecs: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: IslamicEventOccurrence, into buf: inout [UInt8]) {
        FfiConverterTypeIslamicEvent.write(value.event, into: &buf)
        FfiConverterTypeHijriDate.write(value.hijriDate, into: &buf)
        FfiConverterInt64.write(value.gregorianTimestampSecs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIslamicEventOccurrence_lift(_ buf: RustBuffer) throws -> IslamicEventOccurrence {
    return try FfiConverterTypeIslamicEventOccurrence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIslamicEventOccurrence_lower(_ value: IslamicEventOccurrence) -> RustBuffer {
    return FfiConverterTypeIslamicEventOccurrence.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum IslamicEvent: Equatable, Hashable {
    
    case islamicNewYear
    case ashura
    case mawlidAlNabi
    case battleOfHattin
    case battleOfMutah
    case battleOfTabuk
    case israAndMiraj
    case nisfShaban
    case firstOfRamadan
    case battleOfBadr
    case conquestOfMecca
    case laylatAlQadr
    case eidAlFitr
    case battleOfUhud
    case dayOfArafah
    case eidAlAdha





}

#if compiler(>=6)
extension IslamicEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIslamicEvent: FfiConverterRustBuffer {
    typealias SwiftType = IslamicEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IslamicEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .islamicNewYear
        
        case 2: return .ashura
        
        case 3: return .mawlidAlNabi
        
        case 4: return .battleOfHattin
        
        case 5: return .battleOfMutah
        
        case 6: return .battleOfTabuk
        
        case 7: return .israAndMiraj
        
        case 8: return .nisfShaban
        
        case 9: return .firstOfRamadan
        
        case 10: return .battleOfBadr
        
        case 11: return .conquestOfMecca
        
        case 12: return .laylatAlQadr
        
        case 13: return .eidAlFitr
        
        case 14: return .battleOfUhud
        
        case 15: return .dayOfArafah
        
        case 16: return .eidAlAdha
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IslamicEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .islamicNewYear:
            writeInt(&buf, Int32(1))
        
        
        case .ashura:
            writeInt(&buf, Int32(2))
        
        
        case .mawlidAlNabi:
            writeInt(&buf, Int32(3))
        
        
        case .battleOfHattin:
            writeInt(&buf, Int32(4))
        
        
        case .battleOfMutah:
            writeInt(&buf, Int32(5))
        
        
        case .battleOfTabuk:
            writeInt(&buf, Int32(6))
        
        
        case .israAndMiraj:
            writeInt(&buf, Int32(7))
        
        
        case .nisfShaban:
            writeInt(&buf, Int32(8))
        
        
        case .firstOfRamadan:
            writeInt(&buf, Int32(9))
        
        
        case .battleOfBadr:
            writeInt(&buf, Int32(10))
        
        
        case .conquestOfMecca:
            writeInt(&buf, Int32(11))
        
        
        case .laylatAlQadr:
            writeInt(&buf, Int32(12))
        
        
        case .eidAlFitr:
            writeInt(&buf, Int32(13))
        
        
        case .battleOfUhud:
            writeInt(&buf, Int32(14))
        
        
        case .dayOfArafah:
            writeInt(&buf, Int32(15))
        
        
        case .eidAlAdha:
            writeInt(&buf, Int32(16))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIslamicEvent_lift(_ buf: RustBuffer) throws -> IslamicEvent {
    return try FfiConverterTypeIslamicEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIslamicEvent_lower(_ value: IslamicEvent) -> RustBuffer {
    return FfiConverterTypeIslamicEvent.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Mazhab: Equatable, Hashable {
    
    case shafi
    case hanafi





}

#if compiler(>=6)
extension Mazhab: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMazhab: FfiConverterRustBuffer {
    typealias SwiftType = Mazhab

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mazhab {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .shafi
        
        case 2: return .hanafi
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Mazhab, into buf: inout [UInt8]) {
        switch value {
        
        
        case .shafi:
            writeInt(&buf, Int32(1))
        
        
        case .hanafi:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMazhab_lift(_ buf: RustBuffer) throws -> Mazhab {
    return try FfiConverterTypeMazhab.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMazhab_lower(_ value: Mazhab) -> RustBuffer {
    return FfiConverterTypeMazhab.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Method: Equatable, Hashable {
    
    case muslimWorldLeague
    case egyptian
    case ummAlQura
    case moonsightingCommittee
    case northAmerica
    case singapore





}

#if compiler(>=6)
extension Method: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMethod: FfiConverterRustBuffer {
    typealias SwiftType = Method

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Method {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .muslimWorldLeague
        
        case 2: return .egyptian
        
        case 3: return .ummAlQura
        
        case 4: return .moonsightingCommittee
        
        case 5: return .northAmerica
        
        case 6: return .singapore
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Method, into buf: inout [UInt8]) {
        switch value {
        
        
        case .muslimWorldLeague:
            writeInt(&buf, Int32(1))
        
        
        case .egyptian:
            writeInt(&buf, Int32(2))
        
        
        case .ummAlQura:
            writeInt(&buf, Int32(3))
        
        
        case .moonsightingCommittee:
            writeInt(&buf, Int32(4))
        
        
        case .northAmerica:
            writeInt(&buf, Int32(5))
        
        
        case .singapore:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMethod_lift(_ buf: RustBuffer) throws -> Method {
    return try FfiConverterTypeMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMethod_lower(_ value: Method) -> RustBuffer {
    return FfiConverterTypeMethod.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Prayer: Equatable, Hashable {
    
    case fajr
    case sunrise
    case dhuhr
    case asr
    case maghrib
    case ishaa
    case fajrTomorrow





}

#if compiler(>=6)
extension Prayer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrayer: FfiConverterRustBuffer {
    typealias SwiftType = Prayer

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Prayer {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fajr
        
        case 2: return .sunrise
        
        case 3: return .dhuhr
        
        case 4: return .asr
        
        case 5: return .maghrib
        
        case 6: return .ishaa
        
        case 7: return .fajrTomorrow
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Prayer, into buf: inout [UInt8]) {
        switch value {
        
        
        case .fajr:
            writeInt(&buf, Int32(1))
        
        
        case .sunrise:
            writeInt(&buf, Int32(2))
        
        
        case .dhuhr:
            writeInt(&buf, Int32(3))
        
        
        case .asr:
            writeInt(&buf, Int32(4))
        
        
        case .maghrib:
            writeInt(&buf, Int32(5))
        
        
        case .ishaa:
            writeInt(&buf, Int32(6))
        
        
        case .fajrTomorrow:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrayer_lift(_ buf: RustBuffer) throws -> Prayer {
    return try FfiConverterTypePrayer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrayer_lower(_ value: Prayer) -> RustBuffer {
    return FfiConverterTypePrayer.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Provider: Equatable, Hashable {
    
    case darElFatwa(ProviderCity
    )





}

#if compiler(>=6)
extension Provider: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProvider: FfiConverterRustBuffer {
    typealias SwiftType = Provider

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Provider {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .darElFatwa(try FfiConverterTypeProviderCity.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Provider, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .darElFatwa(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeProviderCity.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProvider_lift(_ buf: RustBuffer) throws -> Provider {
    return try FfiConverterTypeProvider.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProvider_lower(_ value: Provider) -> RustBuffer {
    return FfiConverterTypeProvider.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ProviderCity: Equatable, Hashable {
    
    case beirut





}

#if compiler(>=6)
extension ProviderCity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProviderCity: FfiConverterRustBuffer {
    typealias SwiftType = ProviderCity

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProviderCity {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .beirut
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProviderCity, into buf: inout [UInt8]) {
        switch value {
        
        
        case .beirut:
            writeInt(&buf, Int32(1))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProviderCity_lift(_ buf: RustBuffer) throws -> ProviderCity {
    return try FfiConverterTypeProviderCity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProviderCity_lower(_ value: ProviderCity) -> RustBuffer {
    return FfiConverterTypeProviderCity.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeIslamicEventOccurrence: FfiConverterRustBuffer {
    typealias SwiftType = [IslamicEventOccurrence]

    public static func write(_ value: [IslamicEventOccurrence], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeIslamicEventOccurrence.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [IslamicEventOccurrence] {
        let len: Int32 = try readInt(&buf)
        var seq = [IslamicEventOccurrence]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeIslamicEventOccurrence.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeIslamicEvent: FfiConverterRustBuffer {
    typealias SwiftType = [IslamicEvent]

    public static func write(_ value: [IslamicEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeIslamicEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [IslamicEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [IslamicEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeIslamicEvent.read(from: &buf))
        }
        return seq
    }
}
/**
 * Returns all recurring Islamic event occurrences that fall within the given Gregorian year,
 * sorted chronologically by Gregorian date.
 */
public func eventsForGregorianYear(gregorianYear: Int32) -> [IslamicEventOccurrence]  {
    return try!  FfiConverterSequenceTypeIslamicEventOccurrence.lift(try! rustCall() {
    uniffi_miqat_fn_func_events_for_gregorian_year(
        FfiConverterInt32.lower(gregorianYear),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_miqat_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_miqat_checksum_func_events_for_gregorian_year() != 8850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_hijridateinfo_date() != 23426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_hijridateinfo_events() != 27811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_hijridateinfo_to_gregorian() != 54361) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_asr() != 64685) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_current_prayer() != 51578) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_dhuhr() != 1215) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_fajr() != 11752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_fajr_tomorrow() != 47439) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_hijri_date() != 4994) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_ishaa() != 11283) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_maghrib() != 52189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_next_prayer() != 42342) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_method_prayertimes_sunrise() != 23093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_constructor_hijridateinfo_from_timestamp() != 36053) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_constructor_prayertimes_from_method() != 953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_miqat_checksum_constructor_prayertimes_from_precomputed() != 28190) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMiqatInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all