// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package org.ibadalrahman.miqat

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import android.os.Build
import androidx.annotation.RequiresApi
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_miqat_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_miqat_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "miqat"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "miqat"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_miqat_checksum_func_events_for_gregorian_year(
    ): Int
    external fun uniffi_miqat_checksum_func_parameters_for_method(
    ): Int
    external fun uniffi_miqat_checksum_method_hijridateinfo_date(
    ): Int
    external fun uniffi_miqat_checksum_method_hijridateinfo_events(
    ): Int
    external fun uniffi_miqat_checksum_method_hijridateinfo_to_gregorian(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_asr(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_current_prayer(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_dhuhr(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_fajr(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_fajr_tomorrow(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_hijri_date(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_ishaa(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_maghrib(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_next_prayer(
    ): Int
    external fun uniffi_miqat_checksum_method_prayertimes_sunrise(
    ): Int
    external fun uniffi_miqat_checksum_constructor_hijridateinfo_from_timestamp(
    ): Int
    external fun uniffi_miqat_checksum_constructor_prayertimes_from_method(
    ): Int
    external fun uniffi_miqat_checksum_constructor_prayertimes_from_parameters(
    ): Int
    external fun uniffi_miqat_checksum_constructor_prayertimes_from_precomputed(
    ): Int
    external fun ffi_miqat_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "miqat"))
        
    }
    external fun uniffi_miqat_fn_clone_hijridateinfo(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_free_hijridateinfo(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_miqat_fn_constructor_hijridateinfo_from_timestamp(`timestampSecs`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_hijridateinfo_date(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_method_hijridateinfo_events(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_method_hijridateinfo_to_gregorian(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_clone_prayertimes(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_free_prayertimes(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_miqat_fn_constructor_prayertimes_from_method(`dateUtcTimestampSecs`: Long,`coordinates`: RustBuffer.ByValue,`method`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_constructor_prayertimes_from_parameters(`dateUtcTimestampSecs`: Long,`coordinates`: RustBuffer.ByValue,`parameters`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_constructor_prayertimes_from_precomputed(`dateUtcTimestampSecs`: Long,`provider`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_asr(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_current_prayer(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_method_prayertimes_dhuhr(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_fajr(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_fajr_tomorrow(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_hijri_date(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_method_prayertimes_ishaa(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_maghrib(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_method_prayertimes_next_prayer(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_method_prayertimes_sunrise(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_miqat_fn_func_events_for_gregorian_year(`gregorianYear`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_miqat_fn_func_parameters_for_method(`method`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_miqat_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_miqat_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_miqat_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_miqat_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_miqat_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_miqat_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_miqat_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_miqat_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_miqat_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_miqat_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_miqat_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_miqat_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_miqat_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_miqat_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_miqat_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_miqat_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_miqat_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_miqat_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_miqat_checksum_func_events_for_gregorian_year() != 8850) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_func_parameters_for_method() != 40359) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_hijridateinfo_date() != 23426) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_hijridateinfo_events() != 27811) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_hijridateinfo_to_gregorian() != 54361) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_asr() != 64685) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_current_prayer() != 51578) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_dhuhr() != 1215) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_fajr() != 11752) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_fajr_tomorrow() != 47439) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_hijri_date() != 4994) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_ishaa() != 11283) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_maghrib() != 52189) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_next_prayer() != 42342) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_method_prayertimes_sunrise() != 23093) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_constructor_hijridateinfo_from_timestamp() != 36053) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_constructor_prayertimes_from_method() != 953) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_constructor_prayertimes_from_parameters() != 30632) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_miqat_checksum_constructor_prayertimes_from_precomputed() != 28190) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.


private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
        AndroidSystemCleaner()
    } else {
        UniffiJnaCleaner()
    }

// The SystemCleaner, available from API Level 33.
// Some API Level 33 OSes do not support using it, so we require API Level 34.
@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleaner : UniffiCleaner {
    val cleaner = android.system.SystemCleaner.cleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        AndroidSystemCleanable(cleaner.register(value, cleanUpTask))
}

@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleanable(
    private val cleanable: java.lang.ref.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    fun lift(value: Int): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterInt: FfiConverter<Int, Int> {
    override fun lift(value: Int): Int {
        return value
    }

    override fun read(buf: ByteBuffer): Int {
        return buf.getInt()
    }

    override fun lower(value: Int): Int {
        return value
    }

    override fun allocationSize(value: Int) = 4UL

    override fun write(value: Int, buf: ByteBuffer) {
        buf.putInt(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


public interface HijriDateInfoInterface {
    
    fun `date`(): HijriDate
    
    fun `events`(): List<IslamicEvent>
    
    /**
     * Converts this Hijri date back to a Unix timestamp (seconds) at midnight UTC,
     * or `None` if the date cannot be represented.
     */
    fun `toGregorian`(): kotlin.Long?
    
    companion object
}

open class HijriDateInfo: Disposable, AutoCloseable, HijriDateInfoInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_miqat_fn_free_hijridateinfo(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_miqat_fn_clone_hijridateinfo(handle, status)
        }
    }

    override fun `date`(): HijriDate {
            return FfiConverterTypeHijriDate.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_hijridateinfo_date(
        it,
        _status)
}
    }
    )
    }
    

    override fun `events`(): List<IslamicEvent> {
            return FfiConverterSequenceTypeIslamicEvent.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_hijridateinfo_events(
        it,
        _status)
}
    }
    )
    }
    

    
    /**
     * Converts this Hijri date back to a Unix timestamp (seconds) at midnight UTC,
     * or `None` if the date cannot be represented.
     */override fun `toGregorian`(): kotlin.Long? {
            return FfiConverterOptionalLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_hijridateinfo_to_gregorian(
        it,
        _status)
}
    }
    )
    }
    

    

    


    
    companion object {
         fun `fromTimestamp`(`timestampSecs`: kotlin.Long): HijriDateInfo {
            return FfiConverterTypeHijriDateInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_constructor_hijridateinfo_from_timestamp(
    
        FfiConverterLong.lower(`timestampSecs`),_status)
}
    )
    }
    

        
    }
    
}


/**
 * @suppress
 */
public object FfiConverterTypeHijriDateInfo: FfiConverter<HijriDateInfo, Long> {
    override fun lower(value: HijriDateInfo): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): HijriDateInfo {
        return HijriDateInfo(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): HijriDateInfo {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: HijriDateInfo) = 8UL

    override fun write(value: HijriDateInfo, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


public interface PrayerTimesInterface {
    
    fun `asr`(): kotlin.Long
    
    fun `currentPrayer`(): Prayer
    
    fun `dhuhr`(): kotlin.Long
    
    fun `fajr`(): kotlin.Long
    
    fun `fajrTomorrow`(): kotlin.Long
    
    fun `hijriDate`(): HijriDate
    
    fun `ishaa`(): kotlin.Long
    
    fun `maghrib`(): kotlin.Long
    
    fun `nextPrayer`(): Prayer
    
    fun `sunrise`(): kotlin.Long
    
    companion object
}

open class PrayerTimes: Disposable, AutoCloseable, PrayerTimesInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_miqat_fn_free_prayertimes(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_miqat_fn_clone_prayertimes(handle, status)
        }
    }

    override fun `asr`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_asr(
        it,
        _status)
}
    }
    )
    }
    

    override fun `currentPrayer`(): Prayer {
            return FfiConverterTypePrayer.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_current_prayer(
        it,
        _status)
}
    }
    )
    }
    

    override fun `dhuhr`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_dhuhr(
        it,
        _status)
}
    }
    )
    }
    

    override fun `fajr`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_fajr(
        it,
        _status)
}
    }
    )
    }
    

    override fun `fajrTomorrow`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_fajr_tomorrow(
        it,
        _status)
}
    }
    )
    }
    

    override fun `hijriDate`(): HijriDate {
            return FfiConverterTypeHijriDate.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_hijri_date(
        it,
        _status)
}
    }
    )
    }
    

    override fun `ishaa`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_ishaa(
        it,
        _status)
}
    }
    )
    }
    

    override fun `maghrib`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_maghrib(
        it,
        _status)
}
    }
    )
    }
    

    override fun `nextPrayer`(): Prayer {
            return FfiConverterTypePrayer.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_next_prayer(
        it,
        _status)
}
    }
    )
    }
    

    override fun `sunrise`(): kotlin.Long {
            return FfiConverterLong.lift(
    callWithHandle {
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_method_prayertimes_sunrise(
        it,
        _status)
}
    }
    )
    }
    

    

    


    
    companion object {
         fun `fromMethod`(`dateUtcTimestampSecs`: kotlin.Long, `coordinates`: Coordinates, `method`: Method): PrayerTimes {
            return FfiConverterTypePrayerTimes.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_constructor_prayertimes_from_method(
    
        FfiConverterLong.lower(`dateUtcTimestampSecs`),FfiConverterTypeCoordinates.lower(`coordinates`),FfiConverterTypeMethod.lower(`method`),_status)
}
    )
    }
    

         fun `fromParameters`(`dateUtcTimestampSecs`: kotlin.Long, `coordinates`: Coordinates, `parameters`: CalculationParameters): PrayerTimes {
            return FfiConverterTypePrayerTimes.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_constructor_prayertimes_from_parameters(
    
        FfiConverterLong.lower(`dateUtcTimestampSecs`),FfiConverterTypeCoordinates.lower(`coordinates`),FfiConverterTypeCalculationParameters.lower(`parameters`),_status)
}
    )
    }
    

         fun `fromPrecomputed`(`dateUtcTimestampSecs`: kotlin.Long, `provider`: Provider): PrayerTimes {
            return FfiConverterTypePrayerTimes.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_constructor_prayertimes_from_precomputed(
    
        FfiConverterLong.lower(`dateUtcTimestampSecs`),FfiConverterTypeProvider.lower(`provider`),_status)
}
    )
    }
    

        
    }
    
}


/**
 * @suppress
 */
public object FfiConverterTypePrayerTimes: FfiConverter<PrayerTimes, Long> {
    override fun lower(value: PrayerTimes): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): PrayerTimes {
        return PrayerTimes(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): PrayerTimes {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: PrayerTimes) = 8UL

    override fun write(value: PrayerTimes, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * Flat, FFI-friendly view of [`miqat::Parameters`].
 *
 * Ishaa is exposed as a plain angle only. Interval-based Ishaa (e.g. Umm al-Qura's
 * fixed 90 minutes) cannot be expressed here and reads back as `ishaa_angle == 0.0`
 * when querying such a method via [`parameters_for_method`].
 */
data class CalculationParameters (
    /**
     * Solar angle below the horizon for Fajr, in degrees.
     */
    val `fajrAngle`: kotlin.Double
    , 
    /**
     * Solar angle below the horizon for Ishaa, in degrees.
     */
    val `ishaaAngle`: kotlin.Double
    , 
    /**
     * Juristic school affecting the Asr calculation.
     */
    val `mazhab`: Mazhab
    , 
    /**
     * Rule for approximating Fajr and Ishaa at high latitudes.
     */
    val `highLatitudeRule`: HighLatitudeRule
    , 
    /**
     * User-supplied per-prayer offsets, in minutes.
     */
    val `adjustments`: TimeAdjustment
    , 
    /**
     * Preset per-prayer offsets baked into a method (populated when querying a method).
     */
    val `methodAdjustments`: TimeAdjustment
    , 
    /**
     * Output rounding behaviour.
     */
    val `rounding`: Rounding
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCalculationParameters: FfiConverterRustBuffer<CalculationParameters> {
    override fun read(buf: ByteBuffer): CalculationParameters {
        return CalculationParameters(
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterTypeMazhab.read(buf),
            FfiConverterTypeHighLatitudeRule.read(buf),
            FfiConverterTypeTimeAdjustment.read(buf),
            FfiConverterTypeTimeAdjustment.read(buf),
            FfiConverterTypeRounding.read(buf),
        )
    }

    override fun allocationSize(value: CalculationParameters) = (
            FfiConverterDouble.allocationSize(value.`fajrAngle`) +
            FfiConverterDouble.allocationSize(value.`ishaaAngle`) +
            FfiConverterTypeMazhab.allocationSize(value.`mazhab`) +
            FfiConverterTypeHighLatitudeRule.allocationSize(value.`highLatitudeRule`) +
            FfiConverterTypeTimeAdjustment.allocationSize(value.`adjustments`) +
            FfiConverterTypeTimeAdjustment.allocationSize(value.`methodAdjustments`) +
            FfiConverterTypeRounding.allocationSize(value.`rounding`)
    )

    override fun write(value: CalculationParameters, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`fajrAngle`, buf)
            FfiConverterDouble.write(value.`ishaaAngle`, buf)
            FfiConverterTypeMazhab.write(value.`mazhab`, buf)
            FfiConverterTypeHighLatitudeRule.write(value.`highLatitudeRule`, buf)
            FfiConverterTypeTimeAdjustment.write(value.`adjustments`, buf)
            FfiConverterTypeTimeAdjustment.write(value.`methodAdjustments`, buf)
            FfiConverterTypeRounding.write(value.`rounding`, buf)
    }
}



data class Coordinates (
    val `latitude`: kotlin.Double
    , 
    val `longitude`: kotlin.Double
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCoordinates: FfiConverterRustBuffer<Coordinates> {
    override fun read(buf: ByteBuffer): Coordinates {
        return Coordinates(
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: Coordinates) = (
            FfiConverterDouble.allocationSize(value.`latitude`) +
            FfiConverterDouble.allocationSize(value.`longitude`)
    )

    override fun write(value: Coordinates, buf: ByteBuffer) {
            FfiConverterDouble.write(value.`latitude`, buf)
            FfiConverterDouble.write(value.`longitude`, buf)
    }
}



data class HijriDate (
    val `year`: kotlin.Int
    , 
    val `month`: kotlin.UByte
    , 
    val `day`: kotlin.UByte
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeHijriDate: FfiConverterRustBuffer<HijriDate> {
    override fun read(buf: ByteBuffer): HijriDate {
        return HijriDate(
            FfiConverterInt.read(buf),
            FfiConverterUByte.read(buf),
            FfiConverterUByte.read(buf),
        )
    }

    override fun allocationSize(value: HijriDate) = (
            FfiConverterInt.allocationSize(value.`year`) +
            FfiConverterUByte.allocationSize(value.`month`) +
            FfiConverterUByte.allocationSize(value.`day`)
    )

    override fun write(value: HijriDate, buf: ByteBuffer) {
            FfiConverterInt.write(value.`year`, buf)
            FfiConverterUByte.write(value.`month`, buf)
            FfiConverterUByte.write(value.`day`, buf)
    }
}



/**
 * An occurrence of an Islamic event with its associated Hijri date and Gregorian timestamp.
 */
data class IslamicEventOccurrence (
    val `event`: IslamicEvent
    , 
    val `hijriDate`: HijriDate
    , 
    val `gregorianTimestampSecs`: kotlin.Long
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeIslamicEventOccurrence: FfiConverterRustBuffer<IslamicEventOccurrence> {
    override fun read(buf: ByteBuffer): IslamicEventOccurrence {
        return IslamicEventOccurrence(
            FfiConverterTypeIslamicEvent.read(buf),
            FfiConverterTypeHijriDate.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: IslamicEventOccurrence) = (
            FfiConverterTypeIslamicEvent.allocationSize(value.`event`) +
            FfiConverterTypeHijriDate.allocationSize(value.`hijriDate`) +
            FfiConverterLong.allocationSize(value.`gregorianTimestampSecs`)
    )

    override fun write(value: IslamicEventOccurrence, buf: ByteBuffer) {
            FfiConverterTypeIslamicEvent.write(value.`event`, buf)
            FfiConverterTypeHijriDate.write(value.`hijriDate`, buf)
            FfiConverterLong.write(value.`gregorianTimestampSecs`, buf)
    }
}



data class TimeAdjustment (
    val `fajr`: kotlin.Long
    , 
    val `sunrise`: kotlin.Long
    , 
    val `dhuhr`: kotlin.Long
    , 
    val `asr`: kotlin.Long
    , 
    val `maghrib`: kotlin.Long
    , 
    val `ishaa`: kotlin.Long
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTimeAdjustment: FfiConverterRustBuffer<TimeAdjustment> {
    override fun read(buf: ByteBuffer): TimeAdjustment {
        return TimeAdjustment(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: TimeAdjustment) = (
            FfiConverterLong.allocationSize(value.`fajr`) +
            FfiConverterLong.allocationSize(value.`sunrise`) +
            FfiConverterLong.allocationSize(value.`dhuhr`) +
            FfiConverterLong.allocationSize(value.`asr`) +
            FfiConverterLong.allocationSize(value.`maghrib`) +
            FfiConverterLong.allocationSize(value.`ishaa`)
    )

    override fun write(value: TimeAdjustment, buf: ByteBuffer) {
            FfiConverterLong.write(value.`fajr`, buf)
            FfiConverterLong.write(value.`sunrise`, buf)
            FfiConverterLong.write(value.`dhuhr`, buf)
            FfiConverterLong.write(value.`asr`, buf)
            FfiConverterLong.write(value.`maghrib`, buf)
            FfiConverterLong.write(value.`ishaa`, buf)
    }
}




enum class HighLatitudeRule {
    
    MIDDLE_OF_THE_NIGHT,
    SEVENTH_OF_THE_NIGHT,
    TWILIGHT_ANGLE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeHighLatitudeRule: FfiConverterRustBuffer<HighLatitudeRule> {
    override fun read(buf: ByteBuffer) = try {
        HighLatitudeRule.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: HighLatitudeRule) = 4UL

    override fun write(value: HighLatitudeRule, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class IslamicEvent {
    
    ISLAMIC_NEW_YEAR,
    ASHURA,
    MAWLID_AL_NABI,
    BATTLE_OF_HATTIN,
    BATTLE_OF_MUTAH,
    BATTLE_OF_TABUK,
    ISRA_AND_MIRAJ,
    NISF_SHABAN,
    FIRST_OF_RAMADAN,
    BATTLE_OF_BADR,
    CONQUEST_OF_MECCA,
    LAYLAT_AL_QADR,
    EID_AL_FITR,
    BATTLE_OF_UHUD,
    DAY_OF_ARAFAH,
    EID_AL_ADHA;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeIslamicEvent: FfiConverterRustBuffer<IslamicEvent> {
    override fun read(buf: ByteBuffer) = try {
        IslamicEvent.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: IslamicEvent) = 4UL

    override fun write(value: IslamicEvent, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Mazhab {
    
    SHAFI,
    HANAFI;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMazhab: FfiConverterRustBuffer<Mazhab> {
    override fun read(buf: ByteBuffer) = try {
        Mazhab.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Mazhab) = 4UL

    override fun write(value: Mazhab, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Method {
    
    MUSLIM_WORLD_LEAGUE,
    EGYPTIAN,
    UMM_AL_QURA,
    MOONSIGHTING_COMMITTEE,
    NORTH_AMERICA,
    SINGAPORE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMethod: FfiConverterRustBuffer<Method> {
    override fun read(buf: ByteBuffer) = try {
        Method.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Method) = 4UL

    override fun write(value: Method, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Prayer {
    
    FAJR,
    SUNRISE,
    DHUHR,
    ASR,
    MAGHRIB,
    ISHAA,
    FAJR_TOMORROW;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePrayer: FfiConverterRustBuffer<Prayer> {
    override fun read(buf: ByteBuffer) = try {
        Prayer.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Prayer) = 4UL

    override fun write(value: Prayer, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





sealed class Provider {
    
    data class DarElFatwa(
        val v1: org.ibadalrahman.miqat.ProviderCity) : Provider()
        
    {
        

        companion object
    }
    

    

    
    


    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeProvider : FfiConverterRustBuffer<Provider>{
    override fun read(buf: ByteBuffer): Provider {
        return when(buf.getInt()) {
            1 -> Provider.DarElFatwa(
                FfiConverterTypeProviderCity.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: Provider) = when(value) {
        is Provider.DarElFatwa -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterTypeProviderCity.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: Provider, buf: ByteBuffer) {
        when(value) {
            is Provider.DarElFatwa -> {
                buf.putInt(1)
                FfiConverterTypeProviderCity.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class ProviderCity {
    
    BEIRUT;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeProviderCity: FfiConverterRustBuffer<ProviderCity> {
    override fun read(buf: ByteBuffer) = try {
        ProviderCity.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ProviderCity) = 4UL

    override fun write(value: ProviderCity, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class Rounding {
    
    NEAREST,
    CEIL,
    NONE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeRounding: FfiConverterRustBuffer<Rounding> {
    override fun read(buf: ByteBuffer) = try {
        Rounding.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Rounding) = 4UL

    override fun write(value: Rounding, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIslamicEventOccurrence: FfiConverterRustBuffer<List<IslamicEventOccurrence>> {
    override fun read(buf: ByteBuffer): List<IslamicEventOccurrence> {
        val len = buf.getInt()
        return List<IslamicEventOccurrence>(len) {
            FfiConverterTypeIslamicEventOccurrence.read(buf)
        }
    }

    override fun allocationSize(value: List<IslamicEventOccurrence>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIslamicEventOccurrence.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IslamicEventOccurrence>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIslamicEventOccurrence.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeIslamicEvent: FfiConverterRustBuffer<List<IslamicEvent>> {
    override fun read(buf: ByteBuffer): List<IslamicEvent> {
        val len = buf.getInt()
        return List<IslamicEvent>(len) {
            FfiConverterTypeIslamicEvent.read(buf)
        }
    }

    override fun allocationSize(value: List<IslamicEvent>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeIslamicEvent.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<IslamicEvent>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeIslamicEvent.write(it, buf)
        }
    }
}
        /**
         * Returns all recurring Islamic event occurrences that fall within the given Gregorian year,
         * sorted chronologically by Gregorian date.
         */ fun `eventsForGregorianYear`(`gregorianYear`: kotlin.Int): List<IslamicEventOccurrence> {
            return FfiConverterSequenceTypeIslamicEventOccurrence.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_func_events_for_gregorian_year(
    
        FfiConverterInt.lower(`gregorianYear`),_status)
}
    )
    }
    

        /**
         * Resolves a preset [`Method`] into its concrete calculation parameters.
         *
         * For example, `Method::MuslimWorldLeague` yields `fajr_angle: 18.0`,
         * `ishaa_angle: 17.0`, and `method_adjustments.dhuhr: 1`.
         */ fun `parametersForMethod`(`method`: Method): CalculationParameters {
            return FfiConverterTypeCalculationParameters.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_miqat_fn_func_parameters_for_method(
    
        FfiConverterTypeMethod.lower(`method`),_status)
}
    )
    }
    


